// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineGameSaleApp.Data;

namespace OnlineGameSaleApp.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20181010153325_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineGameSaleApp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("MaxAmount");

                    b.Property<decimal>("MinAmount");

                    b.Property<string>("Name");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("OnlineGameSaleApp.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("GameId");

                    b.Property<int>("Ip");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OnlineGameSaleApp.Models.UserApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UserApps");
                });

            modelBuilder.Entity("OnlineGameSaleApp.Models.UserAppsGames", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("UserAppId");

                    b.HasKey("GameId", "UserAppId");

                    b.HasIndex("UserAppId");

                    b.ToTable("UserAppsGames");
                });

            modelBuilder.Entity("OnlineGameSaleApp.Models.Payment", b =>
                {
                    b.HasOne("OnlineGameSaleApp.Models.Game", "Game")
                        .WithOne("Payment")
                        .HasForeignKey("OnlineGameSaleApp.Models.Payment", "GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnlineGameSaleApp.Models.UserAppsGames", b =>
                {
                    b.HasOne("OnlineGameSaleApp.Models.Game", "Game")
                        .WithMany("UserAppsGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineGameSaleApp.Models.UserApp", "UserApp")
                        .WithMany("UserAppsGames")
                        .HasForeignKey("UserAppId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
